# Generated by Django 2.2.5 on 2020-01-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('state', models.BooleanField(default=False, verbose_name='State')),
                ('created_date', models.DateTimeField(verbose_name='Created')),
            ],
        ),
    ]
